language: node_js
node_js:
  - '6'
  - '8'
  - '10'
env:
  - CXX=g++-4.8
before_script:
  - npm install grunt-cli -g # for "grunt build"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - grunt build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb # for tape-run
install:
  - export DISPLAY=':99.0' # for tape-run
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & # for tape-run
  - npm install # for tape-run
