* Core modules and their info files
*/
module.exports = {
  'channel': require('./modules/Channel'),
  'average': require('./modules/Average'),
  'blend': require('./modules/Blend'),
  'blur': require('./modules/Blur'),
  'brightness': require('./modules/Brightness'),
  'edge-detect': require('./modules/EdgeDetect'),
  'ndvi': require('./modules/Ndvi'),
  'crop': require('./modules/Crop'),
  'channel': require('./modules/Channel'),
  'colorbar': require('./modules/Colorbar'),
  'colormap': require('./modules/Colormap'),
  'convolution': require('./modules/Convolution'),
  'crop': require('./modules/Crop'),
  'decode-qr': require('./modules/DecodeQr'),
  'fisheye-gl': require('./modules/FisheyeGl'),
  'dynamic': require('./modules/Dynamic'),
  'blur': require('./modules/Blur'),
  'saturation': require('./modules/Saturation'),
  'average': require('./modules/Average'),
  'blend': require('./modules/Blend'),
  'import-image': require('./modules/ImportImage'),
  'overlay': require('./modules/Overlay'),
  'edge-detect': require('./modules/EdgeDetect'),
  'fisheye-gl': require('./modules/FisheyeGl'),
  'gamma-correction': require('./modules/GammaCorrection'),
  'gradient': require('./modules/Gradient'),
  'import-image': require('./modules/ImportImage'),
  'invert': require('image-sequencer-invert'),
  'ndvi-colormap': require('./modules/NdviColormap'),
  'colorbar': require('./modules/Colorbar'),
  'gamma-correction': require('./modules/GammaCorrection'),
  'convolution': require('./modules/Convolution'),
  'ndvi': require('./modules/Ndvi'),
  'overlay': require('./modules/Overlay'),
  'saturation': require('./modules/Saturation'),
}
